### ISSUE TITLE
How to evaluate page empirically not displaying

### ISSUE THREAD

**Issue by hzyjerry** [amyjko/design-methods#40]
http://faculty.washington.edu/ajko/books/design-methods/how-to-evaluate-empircally.html

<img width="1512" alt="Screen Shot 2019-07-23 at 7 04 59 PM" src="https://user-images.githubusercontent.com/7868138/61759268-d7d32600-ad7c-11e9-8382-9e4908b24101.png">

**Comment by amyjko** [comment]
Thanks! That should result in a 404, but it doesn't (there's a typo in the URL).

**Comment by hzyjerry** [comment]
Traced the error to here :) https://github.com/andyjko/design-methods/blob/master/how-to-evaluate-analytically.html#L31

**Comment by amyjko** [comment]
Thanks for finding it! The broken link is resolved.
