### ISSUE TITLE
Typographical quotes are cool quotes

### ISSUE THREAD

**Issue by drj11** [amyjko/design-methods#47]
I noticed [a couple of days ago](https://twitter.com/drjtwit/status/1289858193070252032) that this page http://faculty.washington.edu/ajko/books/design-methods/what-designers-do.html has mojibake on some quotation marks that appear in the quoted sections.

Since then, you “fixed” it with https://github.com/amyjko/design-methods/commit/499e5e660e59a5a70f6959261bdb12ef74adde51

I think a better fix would be to keep the typographical quotation marks, U+201C and U+201D by the way, and put

    <meta charset="UTF-8">

in the HTML HEAD element. It seems that if your webpage doesn't say its UTF-8 and your web server doesn't say it in the HTTP header, then the browser is still obliged to interpret it as ISO-8859-1.

Safer to put it in the HTML it seems to me.

Word of warning: testing using the browser on the local filesystem won't show the problem with typographical quotes, you have to look at it through a (local) web server.

**Comment by amyjko** [comment]
Thanks for the suggestion! I'll work on this soon.

**Comment by amyjko** [comment]
Changed book platform to Peruse (http://github.com/amyjko/peruse), which handles smart quotes automatically.
