### ISSUE TITLE
How to understand problems

### ISSUE THREAD

**Issue by carlinmack** [amyjko/design-methods#53]
Two small issues:

> No one on the design team had any clue about the the challenges of finding small holes headphone jack holes without sight.

Remove the first "holes"

> |Fresh Air host Terry Gross|http://www.npr.org/programs/fresh-air/archive]

I think the last bracket character should be a pipe so the link renders properly

Many thanks for contributing to open knowledge!

**Comment by amyjko** [comment]
Thank you! These two should be fixed now.
