### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mjslee** [amyjko/design-methods#60]
In Chapter 4, "How to define problems", ~4th paragraph:

"One simple form of knowledge is to derive goals and alues from your data" --> "values" is incorrect.

**Comment by mjslee** [comment]
This happens again later in the chapter:

"A persona is only useful if it’s alid" --> "valid" is incorrect. Perhaps it's some markup issue with the character "v" when used for emphasis/style?

**Comment by amyjko** [comment]
Thanks for reporting Mike! It's a framework issue, not a typo, but I'm amidst releasing a major update, so I'll fix this as part of that soon.

**Comment by amyjko** [comment]
These should be resolved now.
