### ISSUE TITLE
Text and video misalignment in Chapter 3

### ISSUE THREAD

**Issue by namhouw** [amyjko/design-methods#61]
The video is of an INFO 360 student performing a contextual inquiry around **grocery shopping**, however the text still refers to a contextual inquiry from a previous version of the book, where it was about a person observing a **taxi driver.** 

The text: 
"This contextual inquiry is good in that it happens in context. However, it fails in that the researcher is the one driving the conversation, rather than letting the work of the taxi driver determine the conversation. If the latter had happened, there may have been long periods of silence while the driver drove the car, consulted his smartphone, etc."

**Comment by amyjko** [comment]
Thanks for reporting! I'll fix soon.
